== Konzept für motorisierten Slider

=== Einleitung / Rahmenbedingung

Ein Slider ist ein „Schienensystem“ das scheinbar schwebende
Kamerafahrten ermöglicht. Motorisierte Ausführungen sind sehr teuer und
bei unmotorisierten Systemen entsteht wieder eine Verwackslungsgefahr.

=== Ausgangslage / Ist-Situation / Analyse

==== Ausgangssituation

Die HTL Leonding ist eine mittelgroße Schule im Zentralraum OÖ. Einer der vier Ausbildungsrichtungen ist IT-Medientechnik. Dort bildet die Medienproduktion einen der Schwerpunkte der Ausbildung.

==== Ist-Situation

In Videoproduktionen werden seit vielen Jahren Slider verwendet, um
stabile horizontale und vertikale Aufnahmen zu machen. Diese können
motorisiert sein oder nicht.

=== Zielsystem / Sollvorschläge

==== Ziele

Mehr filmbegeisterten Menschen soll die Möglichkeit zum Besitz eines günstigen, motorisierten Slider-Systems geschaffen werden.
Es soll eine App zur praktischeren und bequemeren Verwendung des Systems entwickelt werden.

==== Zielgruppen

Filminteressierte Personen mit sehr kleinem Budget.
Lehrkräfte, die ihren Schülern professionelles Equipment zeigen möchten.
Fotografen, die bewegte Zeitrafferaufnahmen erstellen möchten. 

==== Zielkonflikte

Leicht anwendbares, portables System 
Verkabelungen, 3D Druck, Zerbrechlichkeit

=== Realisierung

Arduino UNO + CNC Shield + Stepper Motor
