== Projektantrag

_Tea Leon & Ehmeir Franziskus_

=== Ausgangssituation

In Videoproduktionen werden seit vielen Jahren Slider verwendet um
stabile horizontale und vertikale Aufnahmen zu machen. Diese können
motorisiert sein oder nicht.

=== Problemstellung

Wenn man versucht per Hand bewegte Aufnahmen zu machen, endet man meist mit verwackeltem oder sogar unbrauchbarem Videomaterial.
Weiters werden die meisten Zeitrafferaufnahmen langweilig, da sie keine Bewegung beinhalten. Die Lösung dieser Probleme wären
motorisierte Slidersysteme. Motorisierte Slider sind sehr teuer und meist unerschwinglich für den durchschnittlichen Anwender.
Billige Alternativen sind unmotorisiert und dadurch entsteht wieder eine Verwackslungsgefahr bzw. unregelmäßige 
Bewegungsgeschwindigkeiten.

=== Aufgabenstellung

Es ist ein erschwingliches Slider-System zu entwickeln, das sowohl horizontale als auch schräge Kamerabewegungen durchführen 
kann. Die montierte Kamera wird einen vorgegeben Streckenabschnitt in einer ebenso vorgegebenen Zeit zurücklegen. 
Somit können z.B. auch Zeitrafferaufnahmen erstellt werden. Der Motor des Sliders wird über einen Micro-Controller 
angesprochen werden. Später wird das System mit einer App gesteuert werden können.

=== Anwendungsfälle

Das System ermöglicht ruhige Kamerabewegungen und bewegte Zeitrafferaufnahmen. Es eignet sich für Personen die für geringes
Geld diese Kamerabewegungen verwenden möchten. Weiters eignet es sich ach für Lehrkräfte, die ihren Schülern einen Einblick in
profesionelles Equipment geben möchten.
